packages:
- '.'
extra-deps:
- binary-instances-1
- binary-orphans-1.0.1
- dbus-1.2.1
- dbus-hslogger-0.1.0.1
- exceptions-0.10.2
- gi-dbusmenu-0.4.1
- gi-gio-2.0.18
- gi-glib-2.0.17
- github-0.24
- haskell-gi-0.21.2
- haskell-gi-base-0.21.1
- spool-0.1
- status-notifier-item-0.3.0.1
- time-compat-1.9.2.2
- transformers-compat-0.6.5
- unordered-containers-0.2.10.0
resolver: lts-13.19
allow-newer: true
nix:
  packages:
    - libdbusmenu-glib
    - gobjectIntrospection
    - libdbusmenu-glib
    - glib
    - libxml2
    - pkgconfig
    - gcc
    - zlib
